INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_OFDM_ALAMOUTI ofdm_alamouti)

FIND_PATH(
    OFDM_ALAMOUTI_INCLUDE_DIRS
    NAMES ofdm_alamouti/api.h
    HINTS $ENV{OFDM_ALAMOUTI_DIR}/include
        ${PC_OFDM_ALAMOUTI_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    OFDM_ALAMOUTI_LIBRARIES
    NAMES gnuradio-ofdm_alamouti
    HINTS $ENV{OFDM_ALAMOUTI_DIR}/lib
        ${PC_OFDM_ALAMOUTI_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OFDM_ALAMOUTI DEFAULT_MSG OFDM_ALAMOUTI_LIBRARIES OFDM_ALAMOUTI_INCLUDE_DIRS)
MARK_AS_ADVANCED(OFDM_ALAMOUTI_LIBRARIES OFDM_ALAMOUTI_INCLUDE_DIRS)

